{{- if .Values.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "template.name" $ }}-ingress
  labels:
    {{- include "template.labels" $ | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - http:
        paths: {{- include "template.port.ingress" $ | nindent 10 }}
{{- end -}}
