{{- if .Values.secrets -}}
{{/* Checks if the release name ends with the expected string. */}}
{{- $postfix := .Values.global.secretPostfix | len | int -}}
{{- $release := $.Release.Name | len | int -}}
{{- $substr := $.Release.Name | substr (sub $release $postfix | int) $release -}}
{{- if ne .Values.global.secretPostfix $substr -}}
  {{- printf "The secret release name \"%s\" must stop with \"%s\"" $.Release.Name .Values.global.secretPostfix | fail -}}
{{- end -}}

{{/* files */}}
{{- range $name, $files := include "template.configmap.file.list" $ | fromJson }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "template.secret.files.name" $ }}{{ $name }}
  labels:
    {{- include "template.labels" $ | nindent 4 }}
stringData:
  {{- range $file := $files }}
  # Path: {{ $file }}
  {{ $file | base }}: |-
    {{- $.Files.Get $file | nindent 4 -}}
  {{- end }}
---
{{- end -}}

{{/* env */}}
{{- range $name, $data := .Values.env }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "template.secret.env.name" $ }}-{{ $name }}
  labels:
    {{- include "template.labels" $ | nindent 4 }}
data:
  {{- range $name, $value := $data }}
  {{ include "template.env.key" $name }}: {{ $value | toString | b64enc }}
  {{- end }}
---
{{- end -}}
{{- end -}}
